# Generated by Django 2.0.6 on 2018-06-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='\\static\\icon-user-default.png', upload_to='images'),
        ),
    ]
