# Generated by Django 2.0.6 on 2018-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180614_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='\\images\\icon-user-default.png', upload_to='images'),
        ),
    ]
